name: Flyway Migration
description: Migrate database in Github Action
branding:
  color: red
  icon: database
inputs:
  url:
    description: The jdbc url to use to connect to the database
    required: true
  user:
    description: The user to use to connect to the database
    required: false
  password:
    description: The password to use to connect to the database
    required: false
  locations:
    description: Comma-separated list of locations to scan recursively for migrations
    required: true
    default: filesystem:./sql
  initSql:
    description: The SQL statements to run to initialize a new database connection immediately after opening it
    required: false
  license:
    description: License key
    required: false
  database_env:
    description: Database  environment
    required: false  
runs:
  using: docker
  image: docker://redgate/flyway:9
  env:
    FLYWAY_URL: ${{ inputs.url }}
    FLYWAY_USER: ${{ inputs.user }}
    FLYWAY_PASSWORD: ${{ inputs.password }}
    FLYWAY_LOCATIONS: ${{ inputs.locations }}
    FLYWAY_INIT_SQL: ${{ inputs.initSql }}
    FLYWAY_LICENSE_KEY: ${{ inputs.license }}
    DATABASE_ENV: ${{ inputs.database_env }}
  args:
    - migrate
    
